apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - PingCAP-QE/artifacts/git-push.yaml
  - pingcap/advanced-statefulset/git-create-tag.yaml
  - pingcap/advanced-statefulset/git-push.yaml
  - pingcap/tidb/git-push-branch-build.yaml
  - pingcap/tidb-operator/git-create-tag.yaml
  - pingcap/tidb-operator/git-push.yaml
  - pingcap/tiflow-operator/git-create-tag.yaml
  - pingcap/tiflow-operator/git-push.yaml
  - pingcap-inc/tici/git-create-tag.yaml
  - pingcap-inc/tici/git-push.yaml
