apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - PingCAP-QE/artifacts/git-push.yaml
  - _/fake-github/fake-github-branch-push-single-platform.yaml
  - _/fake-github/fake-github-branch-push.yaml
  - _/fake-github/fake-github-pr-single-platform.yaml
  - _/fake-github/fake-github-pr.yaml
  - _/fake-github/fake-github-tag-create-single-platform.yaml
  - _/fake-github/fake-github-tag-create.yaml
  - _/git-push-branch-build-community-darwin.yaml
  - _/harbor/cronjobs/fetch-sync-pre-ver-image-tags-to-hub.yaml
  - _/harbor/image-push-on-harbor-for-pingkai.yaml
  - pingcap-inc/tici/git-create-tag.yaml
  - pingcap-inc/tici/git-push.yaml
  - pingcap/ctl/artifact-push-on-harbor.yaml
  - pingcap/ticdc/git-create-tag.yaml
  - pingcap/tidb-binlog/git-push.yaml
  - pingcap/tidb-ctl/git-create-tag.yaml
  - pingcap/tidb-ctl/git-push.yaml
  - pingcap/tidb-tools/git-create-tag.yaml
  - pingcap/tidb-tools/git-push.yaml
  - pingcap/tiflow-operator/git-create-tag.yaml
  - pingcap/tiflow-operator/git-push.yaml
  - pingcap/tiproxy/git-create-tag.yaml
  - pingcap/tiproxy/git-push.yaml
