apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - PingCAP-QE/artifacts/git-push.yaml
  - pingcap/tidb-operator/git-create-tag.yaml
  - pingcap/tidb-operator/git-push.yaml
  - pingcap/tiflow-operator/git-create-tag.yaml
  - pingcap/tiflow-operator/git-push.yaml
