apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - delivery/pingcap-deliver-images.yaml
  - delivery/pingcap-notify-to-deliver-images-to-cloud-tidbx.yaml
  - git-clone.yaml
  - github-set-status.yaml
  - golang-build.yaml
  - golang-test.yaml
  - https://raw.githubusercontent.com/tektoncd/catalog/main/task/kaniko/0.6/kaniko.yaml # kaniko task
  - https://raw.githubusercontent.com/tektoncd/catalog/main/task/ko/0.1/ko.yaml # ko task
  - https://raw.githubusercontent.com/tektoncd/catalog/main/task/tkn/0.4/tkn.yaml # tkn task
  - multi-arch-image-push.yaml
  - pingcap-build-binaries-darwin.yaml
  - pingcap-build-binaries-linux.yaml
  - pingcap-build-images.yaml
  - pingcap-get-builder-image.yaml
  - pingcap-get-set-release-version-v2.yaml
  - pingcap-git-clone-ext.yaml
  - release/create-pr-to-add-release-anchor-commit.yaml
