apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: prow-job-config
    namespace: apps
    behavior: create
    options:
      disableNameSuffixHash: true
    files:
      - pingcap-inc_enterprise-extensions_postsubmits.yaml=pingcap-inc/enterprise-extensions/postsubmits.yaml
      - pingcap-inc_enterprise-extensions_presubmits.yaml=pingcap-inc/enterprise-extensions/presubmits.yaml
      - pingcap-inc_enterprise-plugin_presubmits.yaml=pingcap-inc/enterprise-plugin/presubmits.yaml
      - pingcap-inc_tici_presubmits.yaml=pingcap-inc/tici/presubmits.yaml
      - pingcap-qe_ci_periodics.yaml=pingcap-qe/ci/periodics.yaml
      - pingcap-qe_ci_presubmits.yaml=pingcap-qe/ci/presubmits.yaml
      - pingcap-qe_ee-apps_presubmits.yaml=pingcap-qe/ee-apps/presubmits.yaml
      - pingcap-qe_tidb-test_latest-presubmits-next-gen.yaml=pingcap-qe/tidb-test/latest-presubmits-next-gen.yaml
      - pingcap-qe_tidb-test_latest-presubmits.yaml=pingcap-qe/tidb-test/latest-presubmits.yaml
      - pingcap-qe_tidb-test_release-6.0-presubmits.yaml=pingcap-qe/tidb-test/release-6.0-presubmits.yaml
      - pingcap-qe_tidb-test_release-6.1-presubmits.yaml=pingcap-qe/tidb-test/release-6.1-presubmits.yaml
      - pingcap-qe_tidb-test_release-6.2-presubmits.yaml=pingcap-qe/tidb-test/release-6.2-presubmits.yaml
      - pingcap-qe_tidb-test_release-7.1-presubmits.yaml=pingcap-qe/tidb-test/release-7.1-presubmits.yaml
      - pingcap-qe_tidb-test_release-8.5-presubmits.yaml=pingcap-qe/tidb-test/release-8.5-presubmits.yaml
      - pingcap_community_postsubmits.yaml=pingcap/community/postsubmits.yaml
      - pingcap_community_presubmits.yaml=pingcap/community/presubmits.yaml
      - pingcap_docs_docs-cn-latest-presubmits.yaml=pingcap/docs/docs-cn-latest-presubmits.yaml
      - pingcap_docs_docs-cn-postsubmits.yaml=pingcap/docs/docs-cn-postsubmits.yaml
      - pingcap_docs_docs-latest-presubmits.yaml=pingcap/docs/docs-latest-presubmits.yaml
      - pingcap_docs_docs-postsubmits.yaml=pingcap/docs/docs-postsubmits.yaml
      - pingcap_docs_docs-tidb-operator-postsubmits.yaml=pingcap/docs/docs-tidb-operator-postsubmits.yaml
      - pingcap_monitoring_periodics.yaml=pingcap/monitoring/periodics.yaml
      - pingcap_ng-monitoring_postsubmits.yaml=pingcap/ng-monitoring/postsubmits.yaml
      - pingcap_ticdc_latest-presubmits-next-gen.yaml=pingcap/ticdc/latest-presubmits-next-gen.yaml
      - pingcap_ticdc_latest-presubmits.yaml=pingcap/ticdc/latest-presubmits.yaml
      - pingcap_ticdc_release-9.0-beta-presubmits.yaml=pingcap/ticdc/release-9.0-beta-presubmits.yaml
      - pingcap_tidb-binlog_latest-presubmits.yaml=pingcap/tidb-binlog/latest-presubmits.yaml
      - pingcap_tidb-engine-ext_latest-presubmits.yaml=pingcap/tidb-engine-ext/latest-presubmits.yaml
      - pingcap_tidb-engine-ext_release-6.1-latest-presubmits.yaml=pingcap/tidb-engine-ext/release-6.1-latest-presubmits.yaml
      - pingcap_tidb-operator_latest-presubmits.yaml=pingcap/tidb-operator/latest-presubmits.yaml
      - pingcap_tidb-operator_release-1.x-presubmits.yaml=pingcap/tidb-operator/release-1.x-presubmits.yaml
      - pingcap_tidb-tools_presubmits.yaml=pingcap/tidb-tools/presubmits.yaml
      - pingcap_tidb_common-postsubmits.yaml=pingcap/tidb/common-postsubmits.yaml
      - pingcap_tidb_common-presubmits.yaml=pingcap/tidb/common-presubmits.yaml
      - pingcap_tidb_latest-periodics.yaml=pingcap/tidb/latest-periodics.yaml
      - pingcap_tidb_latest-postsubmits.yaml=pingcap/tidb/latest-postsubmits.yaml
      - pingcap_tidb_latest-presubmits-canary.yaml=pingcap/tidb/latest-presubmits-canary.yaml
      - pingcap_tidb_latest-presubmits-next-gen.yaml=pingcap/tidb/latest-presubmits-next-gen.yaml
      - pingcap_tidb_latest-presubmits.yaml=pingcap/tidb/latest-presubmits.yaml
      - pingcap_tidb_release-6.1-presubmits.yaml=pingcap/tidb/release-6.1-presubmits.yaml
      - pingcap_tidb_release-6.2-presubmits.yaml=pingcap/tidb/release-6.2-presubmits.yaml
      - pingcap_tidb_release-6.3-presubmits.yaml=pingcap/tidb/release-6.3-presubmits.yaml
      - pingcap_tidb_release-6.4-presubmits.yaml=pingcap/tidb/release-6.4-presubmits.yaml
      - pingcap_tidb_release-6.5-20241101-v6.5.7-presubits.yaml=pingcap/tidb/release-6.5-20241101-v6.5.7-presubits.yaml
      - pingcap_tidb_release-6.5-fips-presubmits.yaml=pingcap/tidb/release-6.5-fips-presubmits.yaml
      - pingcap_tidb_release-6.5-presubmits.yaml=pingcap/tidb/release-6.5-presubmits.yaml
      - pingcap_tidb_release-6.5-with-kv-timeout-feature-presubmits.yaml=pingcap/tidb/release-6.5-with-kv-timeout-feature-presubmits.yaml
      - pingcap_tidb_release-6.6-presubmits.yaml=pingcap/tidb/release-6.6-presubmits.yaml
      - pingcap_tidb_release-7.0-presubmits.yaml=pingcap/tidb/release-7.0-presubmits.yaml
      - pingcap_tidb_release-7.1-periodics.yaml=pingcap/tidb/release-7.1-periodics.yaml
      - pingcap_tidb_release-7.1-presubmits.yaml=pingcap/tidb/release-7.1-presubmits.yaml
      - pingcap_tidb_release-7.2-presubmits.yaml=pingcap/tidb/release-7.2-presubmits.yaml
      - pingcap_tidb_release-7.3-presubmits.yaml=pingcap/tidb/release-7.3-presubmits.yaml
      - pingcap_tidb_release-7.4-presubmits.yaml=pingcap/tidb/release-7.4-presubmits.yaml
      - pingcap_tidb_release-7.5-periodics.yaml=pingcap/tidb/release-7.5-periodics.yaml
      - pingcap_tidb_release-7.5-presubmits.yaml=pingcap/tidb/release-7.5-presubmits.yaml
      - pingcap_tidb_release-7.6-presubmits.yaml=pingcap/tidb/release-7.6-presubmits.yaml
      - pingcap_tidb_release-8.0-presubmits.yaml=pingcap/tidb/release-8.0-presubmits.yaml
      - pingcap_tidb_release-8.1-periodics.yaml=pingcap/tidb/release-8.1-periodics.yaml
      - pingcap_tidb_release-8.1-presubmits.yaml=pingcap/tidb/release-8.1-presubmits.yaml
      - pingcap_tidb_release-8.2-presubmits.yaml=pingcap/tidb/release-8.2-presubmits.yaml
      - pingcap_tidb_release-8.3-presubmits.yaml=pingcap/tidb/release-8.3-presubmits.yaml
      - pingcap_tidb_release-8.4-presubmits.yaml=pingcap/tidb/release-8.4-presubmits.yaml
      - pingcap_tidb_release-8.5-presubmits.yaml=pingcap/tidb/release-8.5-presubmits.yaml
      - pingcap_tidb_release-9.0-beta-presubmits.yaml=pingcap/tidb/release-9.0-beta-presubmits.yaml
      - pingcap_tiflash_latest-postsubmits.yaml=pingcap/tiflash/latest-postsubmits.yaml
      - pingcap_tiflash_latest-presubmits-next-gen.yaml=pingcap/tiflash/latest-presubmits-next-gen.yaml
      - pingcap_tiflash_latest-presubmits.yaml=pingcap/tiflash/latest-presubmits.yaml
      - pingcap_tiflash_release-6.1-presubmits.yaml=pingcap/tiflash/release-6.1-presubmits.yaml
      - pingcap_tiflash_release-6.5-presubmits.yaml=pingcap/tiflash/release-6.5-presubmits.yaml
      - pingcap_tiflash_release-7.1-presubmits.yaml=pingcap/tiflash/release-7.1-presubmits.yaml
      - pingcap_tiflash_release-7.5-presubmits.yaml=pingcap/tiflash/release-7.5-presubmits.yaml
      - pingcap_tiflash_release-8.1-presubmits.yaml=pingcap/tiflash/release-8.1-presubmits.yaml
      - pingcap_tiflash_release-8.2-presubmits.yaml=pingcap/tiflash/release-8.2-presubmits.yaml
      - pingcap_tiflash_release-8.3-presubmits.yaml=pingcap/tiflash/release-8.3-presubmits.yaml
      - pingcap_tiflash_release-8.4-presubmits.yaml=pingcap/tiflash/release-8.4-presubmits.yaml
      - pingcap_tiflash_release-8.5-postsubmits.yaml=pingcap/tiflash/release-8.5-postsubmits.yaml
      - pingcap_tiflash_release-8.5-presubmits.yaml=pingcap/tiflash/release-8.5-presubmits.yaml
      - pingcap_tiflash_release-9.0-beta-presubmits.yaml=pingcap/tiflash/release-9.0-beta-presubmits.yaml
      - pingcap_tiflow_common-postsubmits.yaml=pingcap/tiflow/common-postsubmits.yaml
      - pingcap_tiflow_latest-periodics.yaml=pingcap/tiflow/latest-periodics.yaml
      - pingcap_tiflow_latest-postsubmits.yaml=pingcap/tiflow/latest-postsubmits.yaml
      - pingcap_tiflow_latest-presubmits-wip.yaml=pingcap/tiflow/latest-presubmits-wip.yaml
      - pingcap_tiflow_latest-presubmits.yaml=pingcap/tiflow/latest-presubmits.yaml
      - pingcap_tiflow_release-6.0-presubmits.yaml=pingcap/tiflow/release-6.0-presubmits.yaml
      - pingcap_tiflow_release-6.1-presubmits.yaml=pingcap/tiflow/release-6.1-presubmits.yaml
      - pingcap_tiflow_release-6.2-presubmits.yaml=pingcap/tiflow/release-6.2-presubmits.yaml
      - pingcap_tiflow_release-6.5-20241101-v6.5.7-presubmits.yaml=pingcap/tiflow/release-6.5-20241101-v6.5.7-presubmits.yaml
      - pingcap_tiflow_release-6.5-fips-presubmits.yaml=pingcap/tiflow/release-6.5-fips-presubmits.yaml
      - pingcap_tiflow_release-6.5-presubmits.yaml=pingcap/tiflow/release-6.5-presubmits.yaml
      - pingcap_tiflow_release-7.1-presubmits.yaml=pingcap/tiflow/release-7.1-presubmits.yaml
      - pingcap_tiflow_release-7.1.0-presubmits.yaml=pingcap/tiflow/release-7.1.0-presubmits.yaml
      - pingcap_tiflow_release-7.2-presubmits.yaml=pingcap/tiflow/release-7.2-presubmits.yaml
      - pingcap_tiflow_release-7.3-presubmits.yaml=pingcap/tiflow/release-7.3-presubmits.yaml
      - pingcap_tiflow_release-7.4-presubmits.yaml=pingcap/tiflow/release-7.4-presubmits.yaml
      - pingcap_tiflow_release-7.5-presubmits.yaml=pingcap/tiflow/release-7.5-presubmits.yaml
      - pingcap_tiflow_release-7.6-presubmits.yaml=pingcap/tiflow/release-7.6-presubmits.yaml
      - pingcap_tiflow_release-8.0-presubmits.yaml=pingcap/tiflow/release-8.0-presubmits.yaml
      - pingcap_tiflow_release-8.1-presubmits.yaml=pingcap/tiflow/release-8.1-presubmits.yaml
      - pingcap_tiflow_release-8.2-presubmits.yaml=pingcap/tiflow/release-8.2-presubmits.yaml
      - pingcap_tiflow_release-8.3-presubmits.yaml=pingcap/tiflow/release-8.3-presubmits.yaml
      - pingcap_tiflow_release-8.4-presubmits.yaml=pingcap/tiflow/release-8.4-presubmits.yaml
      - pingcap_tiflow_release-8.5-presubmits.yaml=pingcap/tiflow/release-8.5-presubmits.yaml
      - pingcap_tiflow_release-9.0-beta-presubmits.yaml=pingcap/tiflow/release-9.0-beta-presubmits.yaml
      - pingcap_tiproxy_latest-postsubmits.yaml=pingcap/tiproxy/latest-postsubmits.yaml
      - pingcap_tiproxy_latest-presubmits.yaml=pingcap/tiproxy/latest-presubmits.yaml
      - ti-community-infra_configs_postsubmits.yaml=ti-community-infra/configs/postsubmits.yaml
      - ti-community-infra_configs_presubmits.yaml=ti-community-infra/configs/presubmits.yaml
      - ti-community-infra_periodics.yaml=ti-community-infra/periodics.yaml
      - ti-community-infra_prow_presubmits.yaml=ti-community-infra/prow/presubmits.yaml
      - tidbcloud_cloud-storage-engine_latest-presubmits-next-gen.yaml=tidbcloud/cloud-storage-engine/latest-presubmits-next-gen.yaml
      - tikv_community_postsubmits.yaml=tikv/community/postsubmits.yaml
      - tikv_community_presubmits.yaml=tikv/community/presubmits.yaml
      - tikv_copr-test_latest-presubmits.yaml=tikv/copr-test/latest-presubmits.yaml
      - tikv_migration_latest-presubmits.yaml=tikv/migration/latest-presubmits.yaml
      - tikv_pd_common-postsubmits.yaml=tikv/pd/common-postsubmits.yaml
      - tikv_pd_common-presubmits.yaml=tikv/pd/common-presubmits.yaml
      - tikv_pd_latest-presubmits-next-gen.yaml=tikv/pd/latest-presubmits-next-gen.yaml
      - tikv_pd_latest-presubmits.yaml=tikv/pd/latest-presubmits.yaml
      - tikv_pd_release-6.1-presubmits.yaml=tikv/pd/release-6.1-presubmits.yaml
      - tikv_pd_release-6.5-fips-presubmits.yaml=tikv/pd/release-6.5-fips-presubmits.yaml
      - tikv_pd_release-6.5-presubmits.yaml=tikv/pd/release-6.5-presubmits.yaml
      - tikv_pd_release-7.1-presubmits.yaml=tikv/pd/release-7.1-presubmits.yaml
      - tikv_pd_release-7.5-presubmits.yaml=tikv/pd/release-7.5-presubmits.yaml
      - tikv_pd_release-8.1-presubmits.yaml=tikv/pd/release-8.1-presubmits.yaml
      - tikv_pd_release-8.5-presubmits.yaml=tikv/pd/release-8.5-presubmits.yaml
      - tikv_pd_release-9.0-beta-presubmits.yaml=tikv/pd/release-9.0-beta-presubmits.yaml
      - tikv_raft-engine_presubmits.yaml=tikv/raft-engine/presubmits.yaml
      - tikv_rocksdb_latest-presubmits.yaml=tikv/rocksdb/latest-presubmits.yaml
      - tikv_rust-rocksdb_latest-presubmits.yaml=tikv/rust-rocksdb/latest-presubmits.yaml
      - tikv_tikv_common-presubmits.yaml=tikv/tikv/common-presubmits.yaml
      - tikv_tikv_latest-postsubmits.yaml=tikv/tikv/latest-postsubmits.yaml
      - tikv_tikv_latest-presubmits.yaml=tikv/tikv/latest-presubmits.yaml
      - tikv_tikv_release-6.1-presubmits.yaml=tikv/tikv/release-6.1-presubmits.yaml
      - tikv_tikv_release-6.5-presubmits.yaml=tikv/tikv/release-6.5-presubmits.yaml
      - tikv_tikv_release-7.1-presubmits.yaml=tikv/tikv/release-7.1-presubmits.yaml
      - tikv_tikv_release-7.5-presubmits.yaml=tikv/tikv/release-7.5-presubmits.yaml
      - tikv_tikv_release-8.1-presubmits.yaml=tikv/tikv/release-8.1-presubmits.yaml
      - tikv_tikv_release-8.2-presubmits.yaml=tikv/tikv/release-8.2-presubmits.yaml
      - tikv_tikv_release-8.3-presubmits.yaml=tikv/tikv/release-8.3-presubmits.yaml
      - tikv_tikv_release-8.4-presubmits.yaml=tikv/tikv/release-8.4-presubmits.yaml
      - tikv_tikv_release-8.5-presubmits.yaml=tikv/tikv/release-8.5-presubmits.yaml
      - tikv_tikv_release-9.0-beta-presubmits.yaml=tikv/tikv/release-9.0-beta-presubmits.yaml
