swagger: "2.0"
info:
  description: "This is a sync ci data server."
  version: "1.0.0"
  title: "sync ci data server"
  contact:
    email: "lilinghai@pingcap.com"
host: "172.16.5.13"
basePath: "/api/v1"
schemes:
  - "http"
paths:
  /ci/job/sync:
    post:
      summary: "sync ci data to db"
      description: "parse the jenkins job api and log,then sync the result to db"
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Pet object that needs to be added to the store"
          required: true
          schema:
            $ref: "#/definitions/SyncReq"
      responses:
        "200":
          description: OK
definitions:
  SyncReq:
    type: "object"
    properties:
      job:
        type: "string"
      id:
        type: "integer"